name:                glados
version:             0.1.0.0
github:              "EpitechPromo2027/B-FUN-500-TLS-5-2-glados-leo.wehrle"
license:             BSD-3-Clause
author:              "Leo Wehrle, Théodore Magna, Lucien Pineau, Alexis Halchemi, Karim Mohammed"
maintainer:          "some-authors@epitech.eu"
copyright:           "2024 all-authors"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/EpitechPromo2027/B-FUN-500-TLS-5-2-glados-leo.wehrle#readme>

dependencies:
- base >= 4.7 && < 5
- megaparsec
- text
- containers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
  - megaparsec

executables:
  lisp-exe:
    main:                Main.hs
    source-dirs:
    - lisp
    - app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados
    - text


tests:
  lisp-test:
    main:                Spec.hs
    source-dirs:         lisp-test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - glados
    - QuickCheck
    - hspec
    - hspec-discover
    - megaparsec
    - text
