name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache Stack
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl libffi-dev libgmp-dev libncurses-dev
    
    - name: Setup GHCup
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
        source ~/.ghcup/env
        
    - name: Setup Haskell Tools
      run: |
        ghcup install ghc 9.6.6
        ghcup set ghc 9.6.6
        ghcup install stack 3.1.1
        ghcup set stack 3.1.1
        stack setup

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Restore Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
    
    - name: Run Tests
      run: |
        source ~/.ghcup/env
        stack test
        
    - name: Run HLint
      run: |
        curl -sSL https://github.com/ndmitchell/hlint/releases/download/v3.5/hlint-3.5-x86_64-linux.tar.gz | tar -xz
        ./hlint-3.5/hlint src/ lisp/ lisp-test/

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Restore Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.stack
          .stack-work
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
    
    - name: Build Project
      run: |
        source ~/.ghcup/env
        stack build
        
    - name: Create Symlink
      run: |
        ln -s .stack-work/dist/x86_64-linux/ghc-9.6.6/build/lisp-exe/lisp-exe run-lisp
        chmod +x run-lisp
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: glados-executable
        path: run-lisp

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: glados-executable
        
    - name: Run Integration Tests
      run: |
        chmod +x run-lisp
        echo "(+ 1 2)" | ./run-lisp
        echo "(define x 42) x" | ./run-lisp
