name: GLaDOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.6'
          cabal-version: '3.10.3.0'
          stack-version: '3.1.1'
          
      - name: Cache Stack
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          restore-keys: |
            ${{ runner.os }}-stack-

      - name: Install dependencies
        run: |
          stack build --only-dependencies
          
      - name: Run tests
        run: stack test
        
      - name: Run HLint
        run: |
          curl -sSL https://github.com/ndmitchell/hlint/releases/download/v3.5/hlint-3.5-x86_64-linux.tar.gz | tar -xz
          ./hlint-3.5/hlint src/ lisp/ lisp-test/
          
      - name: Build
        run: stack build
          
      - name: Create Executable
        run: |
          ln -s .stack-work/dist/x86_64-linux/ghc-9.6.6/build/lisp-exe/lisp-exe run-lisp
          chmod +x run-lisp
          
      - name: Run Integration Tests
        run: |
          echo "(+ 1 2)" | ./run-lisp
          echo "(define x 42) x" | ./run-lisp
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: glados-executable
          path: run-lisp
