name: Glados ci/cd

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.6'
        cabal-version: '3.10.3.0'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ hashFiles('**/*.cabal') }}
        restore-keys: |
          ${{ runner.os }}-cabal-

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests

    - name: Build
      run: cabal build

    - name: Run tests
      run: cabal test

    - name: Run HLint
      uses: haskell-actions/hlint-setup@v2
      with:
        version: '3.5'

  release:
    name: Create Release
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.6'
        cabal-version: '3.10.3.0'

    - name: Build Release
      run: |
        cabal update
        cabal install --installdir=dist/bin --install-method=copy
        cd dist/bin
        tar czf ../glados.tar.gz *
        cd ../..

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ github.run_number }}
        release_name: Release v${{ github.run_number }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/glados.tar.gz
        asset_name: glados.tar.gz
        asset_content_type: application/gzip