name: GLaDOS Release

on:
  release:
    types: [created]

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.6.6'
          cabal-version: '3.10.3.0'
          stack-version: '3.1.1'

      - name: Cache Stack
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            .stack-work
          key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml.lock', 'package.yaml') }}
          
      - name: Build Release
        run: |
          stack build
          ln -s .stack-work/dist/x86_64-linux/ghc-9.6.6/build/lisp-exe/lisp-exe glados
          chmod +x glados
          
      - name: Create Release Archive
        run: |
          tar -czf glados-${{ github.event.release.tag_name }}.tar.gz glados
          
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: glados-${{ github.event.release.tag_name }}.tar.gz