name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    container:
      image: haskell:9.6.6
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: stack build

      - name: Package Binary
        run: |
          mkdir -p release/
          cp $(stack path --local-install-root)/bin/lisp-exe release/glados
          tar czf glados-${{ github.ref_name }}.tar.gz release/

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            glados-${{ github.ref_name }}.tar.gz

  # - name: Create Release
  # uses: softprops/action-gh-release@v1
  # with:
  #   files: |
  #     glados-${{ github.ref_name }}.tar.gz
  #   body: |
  #     GLaDOS Release ${{ github.ref_name }}
      
  #     ## What's Changed
  #     * LISP Interpreter
  #     * Docker Support
  #     * Automatic Tests
      
  #     ## How to Install
  #     ```bash
  #     tar xzf glados-${{ github.ref_name }}.tar.gz
  #     ./release/glados
  #     ```